language: python
matrix:
  include:
    - python: 2.7
    - python: 3.3
    - python: 3.5
    - language: generic
      os: osx
install:
  - echo building on $TRAVIS_OS_NAME
  - if [ "$TRAVIS_OS_NAME" == "osx" ] ; then brew install python ; fi
  - pip install deepdiff
  - pip install coveralls
  - mkdir -p .bins
  - cd .bins
  - if [ "$TRAVIS_OS_NAME" == "osx" ] ; then NINJA_ZIP=mac ; else NINJA_ZIP=linux ; fi
  - wget https://github.com/martine/ninja/releases/download/v1.4.0/ninja-${NINJA_ZIP}.zip -O ninja-14.zip
  - wget https://github.com/martine/ninja/releases/download/v1.6.0/ninja-${NINJA_ZIP}.zip -O ninja-16.zip
  - unzip ninja-14.zip
  - mv ninja ninja_14
  - unzip ninja-16.zip
  - mv ninja ninja_16
  - chmod +x ninja_14
  - chmod +x ninja_16
  - ln -s ninja_16 ninja
  - ./ninja_14 --version
  - ./ninja_16 --version
  - ./ninja --version
  - PATH=$PWD:$PATH
  - cd ..
script:
  - cd tools
  - coverage run --source=.. --omit=tests.py tests.py --compiler clang --ninja ninja_16
  - coverage run --source=.. --omit=tests.py tests.py --compiler gcc --ninja ninja_16
  - coverage run --source=.. --omit=tests.py tests.py --compiler gcc --ninja ninja_14
  - coverage combine
  - python deploy.py
  - python __init__.py --selftest
  - cd ../examples/console_app/simple
  - python ../../../buildfox.py --ide make --ide-env "touch _test.txt"
  - make
  - if [ ! -f "_test.txt" ] ; then exit 1 ; fi
  - cd ../includepath
  - python ../../../buildfox.py --ide cmake --ide-env "touch _test2.txt"
  - cmake -G "Unix Makefiles"
  - make
  - if [ ! -f "_test2.txt" ] ; then exit 1 ; fi
after_success:
  - if [ "$TRAVIS_OS_NAME" == "linux" ] ; then coveralls ; fi