language: python
python:
  - "3.3"
  - "3.5"
install:
  - pip install deepdiff
  - pip install coveralls
script:
  - cd tests
  - coverage run --source=.. --omit=tests.py tests.py
after_success:
  coveralls