language: python
python:
  - "2.7"
  - "3.3"
  - "3.5"
compiler:
  - gcc
install:
  - pip install deepdiff
  - pip install coveralls
  - mkdir -p .bins
  - cd .bins
  - https://github.com/martine/ninja/releases/download/v1.6.0/ninja-linux.zip
  - unzip ninja-linux.zip
  - chmod +x ninja
  - ./ninja --help
  - cd ..
script:
  - cd tests
  - coverage run --source=.. --omit=tests.py tests.py
  - coverage combine
after_success:
  coveralls