environment:
  global:
    PYTHON: "C:\\Python35"
install:
  - set PATH=%cd%/.bins;%PYTHON%;%PYTHON%/Scripts;%PATH%
  - python --version
  - pip install deepdiff
  - mkdir -p .bins
  - cd .bins
  - wget https://github.com/martine/ninja/releases/download/v1.6.0/ninja-win.zip -O ninja.zip
  - unzip ninja.zip
  - ./ninja --version
  - cd ..
build: off
test_script:
  - call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  - cd tools
  - python deploy.py
  - python bf --selftest
  - cd ..