version: 0.2.{build}
environment:
  global:
    PYTHON: "C:\\Python35"
install:
  - set PATH=%cd%/.bins;%PYTHON%;%PYTHON%/Scripts;%PATH%
  - python --version
  - pip install deepdiff coveralls
  - mkdir -p .bins
  - cd .bins
  - powershell "(New-Object Net.WebClient).DownloadFile('https://github.com/martine/ninja/releases/download/v1.6.0/ninja-win.zip','ninja.zip')"
  - powershell "(new-object -com shell.application).namespace($pwd.Path).CopyHere((new-object -com shell.application).namespace(\"$pwd\ninja.zip\").Items(),16)"
  - ninja --version
  - cd ..
build: off
test_script:
  - call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  - cd tools
  - coverage run --source=.. --omit=tests.py tests.py --compiler msc
  - python deploy.py
  - python __init__.py --selftest
  - cd ..
